# Generated by Django 4.1.7 on 2023-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_files_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='content',
            field=models.FileField(upload_to='prodFiles'),
        ),
    ]
